name: Deploy to Cloudflare Workersq
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to Cloudflare Workers
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: Qlwtwn-QlDoa_Xzpjo2V_ufY678IpcObeT7HitAF
